Repository sql-machine-learning/sqlflow, pull requests merged in 2019-05, with the labels that each got.

#311 run through local train in alps
  sql/alps_submitter.go
  sql/alps_submitter_test.go
  sql/executor.go
Labels: alps

#319 Support run extendedSQL for hive
  .travis.yml
  Dockerfile
  Dockerfile.dev
  sql/alps_submitter.go
  sql/cmd.go
  sql/codegen.go
  sql/column_type.go
  sql/executor.go
  sql/model.go
  sql/verifier.go
  sql/verifier_test.go
  sqlfs/reader.go
  sqlfs/sqlfile_test.go
  sqlfs/table.go
  sqlfs/writer.go
Labels: feature, gohive

#369 Add coverage
  .travis.yml
  Dockerfile.dev
  cmd/sqlflowserver/main_test.go
  scripts/deploy.sh
  scripts/test.sh
Labels: feature
