Repository sql-machine-learning/sqlflow, pull requests merged in 2020-06, with the labels that each got.

#2397 Modify step image build process
  docker/step/Dockerfile
Labels: playground

#2413 Prepare images for playground
  doc/run/k8s/install-sqlflow.yaml
  docker/ci/install-python.bash
  docker/jupyter/Dockerfile
  docker/mysql/Dockerfile
  docker/mysql/install-mysql-server.bash
  docker/server/Dockerfile
  docker/step/Dockerfile
  scripts/travis/install_minikube.sh
Labels: playground

#2414 Polish sqlflow playground k8s config
  doc/run/k8s/install-sqlflow.yaml
  docker/dev/find_fastest_resources.sh
Labels: playground

#2475 A document lists SQLFlow modes
  doc/sqlflow.org_cn/model_list.md
Labels: doc

#2485 Remove unnecessary type
  doc/model_parameter.md
  pkg/attribute/attribute.go
  pkg/attribute/model_parameters.go
Labels: cleanup

#2561 Correct the error message in alisa.go
  pkg/executor/alisa.go
Labels: cleanup
